[package]
name = "aoc-2024-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day1"
path = "day1.rs"

[[bin]]
name = "day2"
path = "day2.rs"

[[bin]]
name = "day3"
path = "day3.rs"

[[bin]]
name = "day5"
path = "day5.rs"